config/routes.rb
Mp3upload::Application.routes.draw do

  resources :songs
  root :to => "songs#index"

end

app/models/song.rb
require 'carrierwave/orm/mongoid'

class Song
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title

  mount_uploader :file, FileUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
 
  def index
    @songs = Song.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @songs }
    end
  end

  def edit
    @song = Song.find(params[:id])
    @song.update_attributes(params[:title])

    if @song.save
      redirect_to(songs_url)
    else
      render :action => "index"
    end
  end

  def create
    @song = Song.new(:title => params[:title])
    @song.file = params[:file]

    respond_to do |format|
      if @song.save 
        format.html { redirect_to(root_url, :notice => 'Song was successfully created.') }
        format.xml  { render :xml => @songs, :status => :created, :location => @songs }
      else
        format.html { render :action => "index" }
        format.xml  { render :xml => @songs.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @song = Song.find(params[:id])

    if @song.update_attributes(params[:title])
      redirect_to(@song, :notice => 'Song was successfully updated.')
    else
      redirect_to(root_path)
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to(root_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mp3upload</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :all %>
  <%= javascript_include_tag 'plupload.min', 'plupload.html5.min' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/songs/_form.html.erb
List Of Audio File Formats Supported:
.mp3 .aac .aif .iff .m3u .mid .mpa .ra .wav .wma

<br />
<div id="filelist"></div>
<br />

<%= form_tag songs_path, :multipart => true do %>
  <div class="field">
    <%= label_tag :title %>
    <%= text_field_tag :title %>
  </div>
  <div class="field" id="pickfiles", href="#">
    <%= label_tag :file %>
    <%= file_field_tag :file %>
    <%= hidden_field_tag :file_cache %>
  </div>
  <div class="actions">
    max_file_size : '10mb'<br>
    <span id="uploadfiles"><%= submit_tag "Upload" %></span>
    or
    <%= link_to 'Cancel', root_path %>
  </div>
<% end %>

app/views/songs/_snippet_form.html.erb
<%= form_tag songs_path, :method => :put do %>
    <%= label_tag :title %>
    <%= text_field_tag :title, "#{@song.title}" %>
    <%= submit_tag "save" %>
<% end %>

app/views/songs/_snippets.html.erb
<% if @songs  %>
   <% @songs.each do |song| %>
     
   <div><br />
     <table>
     <tr>
       <td id="snippet">Title: <%= "#{song.title}" %> <%= link_to "edit", edit_song_path(song), :remote => true %></td>
     </tr>
     <tr>
       <!-- td>< %= link_to "#{song.file.current_path}", song.file.current_path %></td -->
       <td>Path: <%= link_to "#{song.file.url}", song.file.url %></td>
       <!-- td>< %= link_to 'Edit', edit_song_path(song) %></tdi -->
       <td><%= link_to 'Destroy', song, :confirm => 'Are you sure?',
                                        :method => :delete, 
                                        :remote => true,
                                        'data-type' => 'json' %>
       </td>
     </tr>
     </table><br />
  </div>
  <% end %>
<% end %>

app/views/songs/_song.html.erb
    <div><br />
      <table>
      <tr>
        <td id="snippet">Title: <%= "#{song.title}" %> <%= link_to "Edit", edit_song_path(song), :remote => true %></td>
      </tr>
      <tr>
        <!-- td>< %= link_to "#{song.file.current_path}", song.file.current_path %></td -->
        <td>Path: <%= link_to "#{song.file.url}", song.file.url %></td>
        <td><%= link_to 'Destroy', song, :confirm => 'Are you sure?', :method => :delete %>
      </table><br />
    </div>

app/views/songs/edit.js.erb
$("#snippet").html("<%= escape_javascript(render(:partial => "snippet_form"))%>");

app/views/songs/index.html.erb
<h1>mp3upload: a multipart form upload </h1>

<%= render 'form' %>
<p id="notice"><%= notice %></p>
<%= render :partial => "song", :collection => @songs %>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>